export const RECORD_FORM_CONST = {
      derivers : [
        'INICIATIVA PROPIA',
        'SACERDOTE',
        'FAMILIAR',
        'DOCTOR',
        'USUARIO',
        'OTRO',
      ],
      genders : [
        'HOMBRE',
        'MUJER',
        'PREFIERE NO ESPECIFICAR'
      ],
      yesNoOptions : [
        {
          text: 'SI',
          value: true,
        },
        {
          text: 'NO',
          value: false,
        },
      ],
      civilStatus : [
        'SOLTERO',
        'CASADO',
        'VIUDO',
        'DIVORCIADO',
        'UNION LIBRE',
      ],
      workStatus : [
        'DESEMPLEADO',
        'JUBILADO',
        'INDIGENTE',
        'ESTABLE',
        'OTRO',
      ],
      houseStatus : [
        'PROPIA',
        'RENTADA',
        'PRESTADA',
      ],
      hygiene : [
        'BUENA',
        'REGULAR',
        'MALA',
        'DESCUIDADA',
      ],
      medicalServices : [
        'CUALES TENEMOS AQUI?',
        'IMSS',
        'ISSTE',
        'SEGURO POPULAR',
        'SEGURO PRIVADO',
        'DIF',
        'OTRO'
      ],
      derivedAreas : [
        'NEUROLOGÍA',
        'NUTRICIÓN',
        'PSICOLOGÍA',
        'ASESORIA LEGAL',
        'ATENCIÓN ESPIRITUAL',
        'PSIQUIATRIA',
        'INSTITUCIÓN',
        'TALLER DE TANATOLOGÍA',
        'TALLER DE SENTIDO DE LA VIDA',
        'NEUROPSICOLOGÍA',
        'CAPA',
        'HOSPITAL REGIONAL',
        'IMSS',
        'DIF'
      ],
      religions : [
        'CATÓLICA',
        'CATÓLICA/CRISTIANA',
        'TESTIGO DE JEHOVÁ',
        'CULTO SANTA MUERTE',
        'JUDAISMO',
        'CRISTIANA',
        'OTRA',
        'NINGUNA'
      ],
      escolarities: [
        'NINGUNA',
        'PRIMARIA',
        'SECUNDARIA',
        'BACHILLERATO',
        'LICENCIATURA',
        'PRIMARIA INCOMPLETA',
        'SECUNDARIA INCOMPLETA',
        'BACHILLERATO INCOMPLETA',
        'LICENCIATURA INCOMPLETA',
      ],
      whoDerived: [
        'FAMILIAR',
        'DOCTOR',
        'USUARIO',
        'SACERDOTE',
        'INICIATIVA PROPIA',
        'OTRO',
      ],
      recordTypes: [
        'INDIVIDUAL',
        'FAMILIAR',
      ],
      derivationTypes: [
        'INTERNA',
        'EXTERNA'
      ],
      externalAreas: [
        'CAPA',
        'HOSPITAL REGIONAL',
        'IMSS',
        'DIF'
      ],
      patientStatus: [
        'EN CURSO',
        'ALTA ABIERTA',
        'ALTA DEFINITIVA',
        'ALTA VOLUNTARIA',
        'DERIVADO',
        'BAJA',
      ],
      dropTypes: [
        'ALTA VOLUNTARIA',
        'BAJA',
      ],
      professionalWhoAttended: [
        'JAYDI CARREÑO ÁVALOS',
        'ISELA LEÓN LÓPEZ',
        'MARTHA RUTH IÑIGUEZ PULIDO'
      ],
      cities : [
        'ACATIC',
        'AMECA',
        'ARANDAS',
        'ATOTONILCO EL ALTO',
        'AYOTLÁN',
        'CALIFORNIA',
        'CAÑADAS DE OBREGON',
        'CUITZEO',
        'CUQUIO',
        'GUADALAJARA',
        'HOSTOTIPAQUILLO',
        'IXTLAHUACÁN DEL RIO',
        'JALOSTOTILÁN',
        'JESUS MARÍA',
        'LA BARCA',
        'LAGOS DE MORENO',
        'LA JOYA',
        'LEON , GUANAJUATO',
        'MEXTICACAN',
        'MEZCALA',
        'NOCHISTLÁN JALISCO',
        'NOCHISTLÁN ZACATECAS',
        'OCOTLÁN',
        'TOTOTLÁN',
        'SAN IGNACIO CERRO GORDO',
        'SAN JOSÉ DE LOS REYNOSOS',
        'SAN JUAN DE LOS LAGOS',
        'SAN JULIÁN',
        'SAN MIGUEL EL ALTO',
        'SAN SEBASTIAN DEL ALAMO',
        'TECOMATLAN',
        'TEOCALTICHE',
        'TEPATITLÁN DE MORELOS',
        'TEQUILILLA',
        'TLAQUEPAQUE',
        'TONALÁ',
        'TOTOTLÁN',
        'YAHUALICA',
        'ZAPOTLANEJO',
      ],
      locations: [
        'CAPILLA DE GUADALUPE',
        'CAPILLA DE MILPILLAS',
        'CERRO GORDO',
        'CRISTO REY',
        'OJO DE AGUA DE LATILLAS',
        'OJO DE AGUA, TEPATITLAN',
        'PAREDONES',
        'PEGUEROS',
        'PURISIMA DEL RINCÓN, GUANAJUATO',
        'RANCHO LA MOTA- CAMINO A TOTOTLAN',
        'RANCHO LOS CHARCOS',
        'SAN DIEGO DE ALEJANDRIA',
        'SAN FRANCISCO DE ASIS',
        'SAN AGUSTÍN',
        'SAN JOSE DE GRACIA',
        'SANTA MARIA DEL VALLE',
        'UNIÓN DE SAN ANTONIO',
        'VALLE DE GUADALUPE',
      ],
      parishes: [
        'NUESTRA SEÑORA DEL REFUGIO',
        'SAN JUAN BAUTISTA',
        'VIRGEN DE LA CANDELARIA',
        'MARÍA AUXILIADORA',
        'NUESTRA SEÑORA DE LA LUZ',
        'NUESTRA SEÑORA DE GUADALUPE',
        'VIRGEN DE LA INMACULADA CONCEPCIÓN',
        'SAN BASILIO EL GRANDE',
        'SAN RODRIGO',
        'SAN ANTONIO',
        'SAN FRANCISCO',
        'NUESTRA SEÑORA DEL FAVOR',
        'CUERPO Y SANGRE DE CRISTO',
        'NUESTRA SEÑORA DE LA ASUNCIÓN',
        'NUESTRA SEÑORA DE GUADALUPE',
        'SAN PEDRO ESQUEDA',
        'MIGUEL ARCÁNGEL',
        'SANTO TORIBIO',
        'JESÚS MARÍA Y JOSÉ',
        'SAGRADA FAMILIA SAN JOSÉ OBRERO',
        'LA INMACULADA CONCEPCIÓN',
        'NUESTRA SEÑORA DE LA PURIFICACIÓN Y SAN JOSÉ',
        'NUESTRA SEÑORA DEL PERPETUO SOCORRO',
        'SANTIAGO APÓSTOL',
        'NUESTRA SEÑORA DEL CARMEN',
        'SAN AGUSTÍN',
        'SAN IGNACIO DE LOYOLA',
        'LA SANTÍSIMA TRINIDAD',
        'SAN JOSÉ',
        'ESPÍRITU SANTO',
        'LA SANGRE DE CRISTO',
        'NUESTRA SEÑORA DEL ROSARIO',
        'SAN FELIPE DE JESÚS',
        'SAGRADA FAMILIA',
        'SAN ISIDRO',
        'SAN MIGUEL ARCÁNGEL',
        'SEÑOR DE LA MISERICORDIA',
        'SANTA MARÍA DE GUADALUPE',
        'NUESTRA SEÑORA DE GUADALUPE',
        'CRISTO REY',
        'LA DIVINA PROVIDENCIA',
        'NUESTRA SEÑORA DE GUADALUPE',
        'NUESTRA SEÑORA DEL CARMEN',
        'ESPÍRITU SANTO',
        'REINA Y MADRE DE LOS CAMPESINOS',
        'LA ROSA MÍSTICA',
        'SAGRADA FAMILIA',
        'SAN ANTONIO',
        'SAN FELIPE DE JESÚS',
        'SANTA CRUZ',
        'SANTA MÓNICA',
        'SANTÍSIMA TRINIDAD',
        'NUESTRA SEÑORA DE GUADALUPE',
        'LA INMACULADA CONCEPCIÓN',
        'NUESTRA SEÑORA DEL ROSARIO',
        'SANTA CECILIA',
        'SAGRADO CORAZÓN DE JESÚS'
    ]
};
