export const RECORD_FORM_CONST = {
      derivers : [
        'INICIATIVA PROPIA',
        'SACERDOTE',
        'FAMILIAR',
        'DOCTOR',
        'USUARIO',
        'OTRO',
      ],
      genders : [
        'HOMBRE',
        'MUJER',
        'PREFIERE NO ESPECIFICAR'
      ],
      yesNoOptions : [
        {
          text: 'SI',
          value: true,
        },
        {
          text: 'NO',
          value: false,
        },
      ],
      civilStatus : [
        'SOLTERO',
        'CASADO',
        'VIUDO',
        'DIVORCIADO',
        'UNION LIBRE',
      ],
      workStatus : [
        'DESEMPLEADO',
        'JUBILADO',
        'INDIGENTE',
        'ESTABLE',
        'OTRO',
      ],
      houseStatus : [
        'PROPIA',
        'RENTADA',
        'PRESTADA',
      ],
      hygiene : [
        'BUENA',
        'REGULAR',
        'MALA',
        'DESCUIDADA',
      ],
      medicalServices : [
        'IMSS',
        'ISSTE',
        'SEGURO P.',
        'PRIVADO',
      ],
      derivedAreas : [
        'NEUROLOGÍA',
        'NUTRICIÓN',
        'PSICOLOGÍA',
        'ASESORIA LEGAL',
        'ATENCIÓN ESPIRITUAL',
        'PSIQUIATRIA',
        'INSTITUCIÓN',
        'TALLER DE TANATOLOGÍA',
        'TALLER DE SENTIDO DE LA VIDA',
        'NEUROPSICOLOGÍA',
      ],
      religions : [
        'CATÓLICA',
        'CATÓLICA/CRISTIANA',
        'TESTIGO DE JEHOVÁ',
        'CULTO SANTA MUERTE',
        'PRIMARIA',
        'JUDAISMO',
        'CRISTIANA',
        'OTRA'
      ],
      escolarities: [
        'NINGUNA',
        'PRIMARIA COMPLETA',
        'SECUNDARIA COMPLETA',
        'BACHILLERATO COMPLETA',
        'LICENCIATURA COMPLETA',
        'PRIMARIA INCOMPLETA',
        'SECUNDARIA INCOMPLETA',
        'BACHILLERATO INCOMPLETA',
        'LICENCIATURA INCOMPLETA',
      ],
      whoDerived: [
        'FAMILIAR',
        'DOCTOR',
        'USUARIO',
        'SACERDOTE',
        'INICIATIVA PROPIA',
        'OTRO',
      ],
      recordTypes: [
        'INDIVIDUAL',
        'FAMILIAR',
      ],
      patientStatus: [
        'EN CURSO',
        'ALTA ABIERTA',
        'ALTA DEFINITIVA',
        'DERIVADO',
        'BAJA',
      ],
      professionalWhoAttended: [
        'JAYDI CARREÑO ÁVALOS',
        'ISELA LEÓN LÓPEZ',
        'MARTHA RUTH IÑIGUEZ PULIDO'
      ],
      cities : [
        'ACATIC',
        'AMECA',
        'ARANDAS',
        'ATOTONILCO EL ALTO',
        'AYOTLÁN',
        'CALIFORNIA',
        'CAÑADAS DE OBREGON',
        'CAPILLA DE GUADALUPE',
        'CAPILLA DE MILPILLAS',
        'CERRO GORDO',
        'CRISTO REY',
        'CUITZEO',
        'CUQUIO',
        'GUADALAJARA',
        'HOSTOTIPAQUILLO',
        'IXTLAHUACÁN DEL RIO',
        'JALOSTOTILÁN',
        'JESUS MARÍA',
        'LA BARCA',
        'LAGOS DE MORENO',
        'LA JOYA',
        'LEON , GUANAJUATO',
        'MEXTICACAN',
        'MEZCALA',
        'NOCHISTLÁN JALISCO',
        'NOCHISTLÁN ZACATECAS',
        'OCOTLÁN',
        'OJO DE AGUA DE LATILLAS',
        'OJO DE AGUA, TEPATITLAN',
        'PAREDONES',
        'PEGUEROS',
        'PURISIMA DEL RINCÓN, GUANAJUATO',
        'RANCHO LA MOTA- CAMINO A TOTOTLAN',
        'RANCHO LOS CHARCOS',
        'SAN AGUSTÍN, TOTOTLÁN',
        'SAN DIEGO DE ALEJANDRIA',
        'SAN FRANCISCO DE ASIS',
        'SAN IGNACIO CERRO GORDO',
        'SAN JOSE DE GRACIA',
        'SAN JOSÉ DE LOS REYNOSOS',
        'SAN JUAN DE LOS LAGOS',
        'SAN JULIÁN',
        'SAN MIGUEL EL ALTO',
        'SAN SEBASTIAN DEL ALAMO',
        'SANTA MARIA DEL VALLE ARANDAS',
        'TECOMATLAN',
        'TEOCALTICHE',
        'TEPATITLÁN DE MORELOS',
        'TEQUILILLA',
        'TLAQUEPAQUE',
        'TONALÁ',
        'TOTOTLÁN',
        'UNIÓN DE SAN ANTONIO',
        'VALLE DE GUADALUPE',
        'YAHUALICA',
        'ZAPOTLANEJO'
      ]
};
