export const SESSION_FORM_CONST = {
  sessionTypes: [
    'NEUROLOGÍA',
    'NUTRICIÓN',
    'PSICOLOGÍA',
    'ASESORIA LEGAL',
    'ATENCIÓN ESPIRITUAL',
    'PSIQUIATRIA',
    'INSTITUCIÓN',
    'TALLER DE TANATOLOGÍA',
    'TALLER DE SENTIDO DE LA VIDA',
    'NEUROPSICOLOGÍA',
    'OTRO',
  ]
};
